apiVersion: v1
kind: Service
metadata:
        name: code-server
spec:
        ports: 
        - port: 80
          targetPort: 8080
        selector:
                app: code-server
---
apiVersion: apps/v1  
kind: Deployment
metadata:
        labels:
                app: code-server
        name: code-server
spec:
        selector:
                matchLabels:
                        app: code-server
        replicas: 1
        template:
                metadata:
                        labels:
                                app: code-server
                spec:
                        containers:
                                - image: codercom/code-server:v2
                                  imagePullPolicy: Always
                                  name: code-server
                                  volumeMounts:
                                          - mountPath: /home/coder 
                                            name: code-server
                                  ports:
                                          - containerPort: 8080
                                  env:
                                          - name: PASSWORD
                                            valueFrom:
                                                    secretKeyRef: 
                                                        name: code-server
                                                        key: password
                        initContainers:
                          - name: init-mount
                            image: busybox
                            command: ["/bin/chmod", "-R", "777", "/data"]
                            volumeMounts:
                              - name: code-server
                                mountPath: /data
                        volumes:
                                - name: code-server
                                  persistentVolumeClaim:
                                          claimName: code-server-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: code-server-pvc
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage:
                                5Gi
        storageClassName: do-block-storage