apiVersion: v1
kind: Namespace
metadata:
        name: code-server
---
apiVersion: v1  
kind: Deployment
metadata:
        labels:
                app: code-server
        name: code-server
        namespace: code-server
spec:
        selector:
                matchLabels:
                        app: code-server
        replicas: 1
        template:
                metadata:
                        labels:
                                app: code-server
                spec:
                        containers:
                                - image: codercom/code-server
                                  imagePullPolicy: always
                                  name: code-server
                                  ports:
                                          - containerPort: 8443
                                  env:
                                          - name: PASSWORD
                                            valueFrom:
                                                    secretKeyRef: 
                                                        name: code-server
                                                        key: password

