apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: directus
  labels:
    app: directus
spec:
  type: NodePort
  ports:
   - port: 80
  selector:
   app: directus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:v8-apache
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DIRECTUS_APP_ENV
              value: "production"
            - name: DIRECTUS_AUTH_PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name: "directus-secrets"
                  key: "DIRECTUS_AUTH_PUBLICKEY"
            - name: DIRECTUS_AUTH_SECRETKEY
              valueFrom:
                  secretKeyRef:
                    name: "directus-secrets"
                    key: "DIRECTUS_AUTH_SECRETKEY"
            - name: DIRECTUS_DATABASE_HOST
              value: "mysql"
            - name: DIRECTUS_DATABASE_PORT
              value: "3306"
            - name: "DIRECTUS_DATABASE_NAME"
              value: "directus"
            - name: "DIRECTUS_DATABASE_USERNAME"
              value: "directus"
            - name: "DIRECTUS_DATABASE_PASSWORD"
              valueFrom:
                  secretKeyRef:
                    name: "mysql-secrets"
                    key: "MYSQL_PASSWORD"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/directus/config
              name: config
            - mountPath: /var/directus/public/uploads
              name: uploads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: directus-config-pvc
        - name: uploads
          persistentVolumeClaim:
              claimName: directus-uploads-pvc