apiVersion: v1
kind: Service
metadata:
  name: famtime
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: famtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: famtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: famtime
  template:
    metadata:
      labels:
        app: famtime
    spec:
      containers:
      - name: famtime
        image: horizonshadow/famtime
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: ROOT_URL
          value: "https://famtime.grep.sh"
        - name: MONGO_URL
          value: "mongodb://mongo:27017/aa2gd-meteor"
        - name: "METEOR_SETTINGS"
          valueFrom: 
            secretKeyRef:
              name: "famtime-secrets"
              key: "METEOR_SETTINGS"
