apiVersion: v1
kind: Service
metadata:
  name: gnashblade
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gnashblade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnashblade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnashblade
  template:
    metadata:
      labels:
        app: gnashblade
    spec:
      containers:
      - name: gnashblade
        image: horizonshadow/gnashblade
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: ROOT_URL
          value: "https://secret-santa-2.grep.sh"
        - name: MONGO_URL
          value: "mongodb://mongo:27017/gnashblade"