apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - famti.me
    - secret-santa-2.grep.sh
    - sc2overwatch.grep.sh
    - gnashblade.grep.sh
    - code.grep.sh
    secretName: letsencrypt-prod
  rules:
  - host: code.grep.sh
    http:
            paths:
                    - backend:
                            serviceName: code-server
                            servicePort: 80
  - host: famti.me
    http:
      paths:
      - backend:
          serviceName: famtime
          servicePort: 80
  - host: secret-santa-2.grep.sh
    http:
      paths:
      - backend:
          serviceName: secret-santa
          servicePort: 80
  - host: sc2overwatch.grep.sh
    http:
      paths:
      - backend:
          serviceName: sc2overwatch
          servicePort: 80
  - host: gnashbla.de
    http:
      paths:
      - backend:
          serviceName: gnashblade
          servicePort: 80
