apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - famtime.grep.sh
    - secret-santa-2.grep.sh
    secretName: letsencrypt-prod
  rules:
  - host: famtime.grep.sh
    http:
      paths:
      - backend:
          serviceName: famtime
          servicePort: 80
  - host: secret-santa-2.grep.sh
    http:
      paths:
      - backend:
          serviceName: secret-santa
          servicePort: 80