apiVersion: v1
kind: Service
metadata:
  name: juiceboxify
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4567
  selector:
    app: juiceboxify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceboxify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceboxify
  template:
    metadata:
      labels:
        app: juiceboxify
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: juiceboxify
        image: docker.pkg.github.com/joshleblanc/juiceboxify.me/juiceboxify
        ports:
        - containerPort: 4567
        imagePullPolicy: Always
        env:
        - name: RACK_ENV
          value: "production"
        - name: azure_face_api_key
          valueFrom:
            secretKeyRef:
              name: "juiceboxify-secrets"
              key: "azure_face_api_key"
        - name: aws_access_key_id
          valueFrom:
            secretKeyRef:
              name: "juiceboxify-secrets"
              key: "aws_access_key_id"
        - name: aws_secret_access_key
          valueFrom:
            secretKeyRef:
              name: "juiceboxify-secrets"
              key: "aws_secret_access_key"