apiVersion: v1
kind: Service
metadata:
  name: secret-santa
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: secret-santa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-santa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-santa
  template:
    metadata:
      labels:
        app: secret-santa
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: secret-santa
        image: docker.pkg.github.com/joshleblanc/secret-santa/secret-santa
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: ROOT_URL
          value: "https://secret-santa.grep.sh"
        - name: MONGO_URL
          value: "mongodb://mongo:27017/secret-santa"
        - name: MAIL_URL
          valueFrom:
            secretKeyRef:
              name: "secret-santa-settings"
              key: "MAIL_URL"
        - name: "METEOR_SETTINGS"
          valueFrom: 
            secretKeyRef:
              name: "secret-santa-settings"
              key: "METEOR_SETTINGS"
