apiVersion: v1
kind: Service
metadata:
  name: yuelabot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4567
  selector:
    app: yuelabot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuelabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuelabot
  template:
    metadata:
      labels:
        app: yuelabot
    spec:
      containers:
      - name: yuelabot
        ports:
        - containerPort: 4567
        image: horizonshadow/yuelabot
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: yuelabot-secrets